In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\USER\Desktop\python.DA\largest Us coys")
df

,Unnamed: 0,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,0,1,Walmart,Retail,"648,125",6.0%,"2,100,000","Bentonville, Arkansas"
1,1,2,Amazon,Retail and cloud computing,"574,785",11.9%,"1,525,000","Seattle, Washington"
2,2,3,Apple,Electronics industry,"383,482",-2.8%,"161,000","Cupertino, California"
3,3,4,UnitedHealth Group,Healthcare,"371,622",14.6%,"440,000","Minnetonka, Minnesota"
4,4,5,Berkshire Hathaway,Conglomerate,"364,482",20.7%,"396,500","Omaha, Nebraska"
...,...,...,...,...,...,...,...,...
95,95,96,TIAA,Financials,"45,735",11.8%,"16,023","New York City, New York"
96,96,97,CHS,Agriculture cooperative,"45,590",-4.6%,"10,609","Inver Grove Heights, Minnesota"
97,97,98,Bristol-Myers Squibb,Pharmaceutical industry,"45,006",-2.5%,"34,100","New York City, New York"
98,98,99,Dow Chemical Company,Chemical industry,"44,622",-21.6%,"35,900","Midland, Michigan"
99,99,100,Best Buy,Retail,"43,452",-6.1%,"85,000","Richfield, Minnesota"

In [8]:
df.info

<bound method DataFrame.info of     Unnamed: 0  Rank                  Name                    Industry  \
0            0     1               Walmart                      Retail
1            1     2                Amazon  Retail and cloud computing
2            2     3                 Apple        Electronics industry
3            3     4    UnitedHealth Group                  Healthcare
4            4     5    Berkshire Hathaway                Conglomerate
..         ...   ...                   ...                         ...
95          95    96                  TIAA                  Financials
96          96    97                   CHS     Agriculture cooperative
97          97    98  Bristol-Myers Squibb     Pharmaceutical industry
98          98    99  Dow Chemical Company           Chemical industry
99          99   100              Best Buy                      Retail

   Revenue (USD millions) Revenue growth  Employees  \
0                 648,125           6.0%  2,100,000
1                 574,785          11.9%  1,525,000
2                 383,482          -2.8%    161,000
3                 371,622          14.6%    440,000
4                 364,482          20.7%    396,500
..                    ...            ...        ...
95                 45,735          11.8%     16,023
96                 45,590          -4.6%     10,609
97                 45,006          -2.5%     34,100
98                 44,622         -21.6%     35,900
99                 43,452          -6.1%     85,000

                      Headquarters
0            Bentonville, Arkansas
1              Seattle, Washington
2            Cupertino, California
3            Minnetonka, Minnesota
4                  Omaha, Nebraska
..                             ...
95         New York City, New York
96  Inver Grove Heights, Minnesota
97         New York City, New York
98               Midland, Michigan
99            Richfield, Minnesota

[100 rows x 8 columns]>

In [10]:
df.describe()

       Unnamed: 0        Rank
count  100.000000  100.000000
mean    49.500000   50.500000
std     29.011492   29.011492
min      0.000000    1.000000
25%     24.750000   25.750000
50%     49.500000   50.500000
75%     74.250000   75.250000
max     99.000000  100.000000

In [12]:
df.isnull().sum()

Unnamed: 0                0
Rank                      0
Name                      0
Industry                  0
Revenue (USD millions)    0
Revenue growth            0
Employees                 0
Headquarters              0
dtype: int64

In [40]:
df.nunique()

Unnamed: 0                100
Rank                      100
Name                      100
Industry                   37
Revenue (USD millions)     98
Revenue growth             96
Employees                  98
Headquarters               71
dtype: int64

In [118]:
#What are the top 10 companies by revenue?
df2= df.sort_values(by= 'Revenue (USD millions)', ascending= False).head(10)
selected_columns= df2[['Name', 'Revenue (USD millions)']]
print(selected_columns)

                       Name Revenue (USD millions)
39                    Tesla                 96,773
40           Morgan Stanley                 96,194
41        Johnson & Johnson                 95,195
42   Archer Daniels Midland                 93,935
43                  PepsiCo                 91,471
44    United Parcel Service                 90,958
45                    FedEx                 90,155
46  The Walt Disney Company                 88,898
47        Dell Technologies                 88,425
48                   Lowe's                 86,377

In [138]:
#Which industry sectors have the most companies?
df['Industry'].value_counts().sort_values(ascending= False).head(10)

Industry
Financials                        13
Retail                            10
Petroleum industry                 9
Pharmaceutical industry            6
Technology                         6
Healthcare                         6
Insurance                          5
Telecommunications                 3
Airline                            3
Technology and cloud computing     3
Name: count, dtype: int64

In [188]:
#What is the average, median, and range of revenues among the top 10 companies?
df2= df.sort_values(by= 'Revenue (USD millions)', ascending= False).head(10)
selected_columns= df2[['Name', 'Revenue (USD millions)']]
df3= print(selected_columns)
df2['Revenue (USD millions)'] = pd.to_numeric(df2['Revenue (USD millions)'].str.replace(',', ''))
average = df2['Revenue (USD millions)'].mean()
median = df2['Revenue (USD millions)'].median()
range_ = df2['Revenue (USD millions)'].max() - df2['Revenue (USD millions)'].min()

print(f"Average: {average}")
print(f"Median: {median}")
print(f"Range: {range_}")

                       Name Revenue (USD millions)
39                    Tesla                 96,773
40           Morgan Stanley                 96,194
41        Johnson & Johnson                 95,195
42   Archer Daniels Midland                 93,935
43                  PepsiCo                 91,471
44    United Parcel Service                 90,958
45                    FedEx                 90,155
46  The Walt Disney Company                 88,898
47        Dell Technologies                 88,425
48                   Lowe's                 86,377
Average: 91838.1
Median: 91214.5
Range: 10396